# Traefik static configuration file (/etc/traefik/traefik.yml)
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration
# and https://doc.traefik.io/traefik/reference/static-configuration/cli/

global:
  checknewversion: true                       # Periodically check if a new version has been released.
  sendanonymoususage: true                    # Periodically send anonymous usage statistics.

log:
  level: debug
  # filePath: /var/log/traefik/traefik.log

accesslog:
  bufferingSize: 100
  filters:
    statusCodes: 204-299,400-499,500-599
  fields:
    headers:
      names:
        Content-Type: keep
        Referer: keep
        User-Agent: keep

api:
  dashboard: true                             # Enable the dashboard
  insecure: false
  debug: true

# Certificate Resolvers are responsible for retrieving certificates from an ACME server
# See https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      dnschallenge:
        provider: cloudflare
        resolvers: 1.1.1.1:53,1.0.0.1:53
        disablepropagationcheck: true
      email: "eric@tripsit.me"                # Email address used for registration
      storage: "/letsencrypt/acme.json"       # File or key used for certificates storage

entryPoints:
  web:
    address: ":80"                            # Create the HTTP entrypoint on port 80
  #   http:
  #     redirections:                           # HTTPS redirection (80 to 443)
  #       entryPoint:
  #         to: "websecure"                     # The target element
  #         scheme: "https"                     # The redirection target scheme
  # websecure:
  #   address: ":443"                           # Create the HTTPS entrypoint on port 443
  #   forwardedHeaders:
  #     trustedIPs: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
  #   http:
  #     tls:
  #       certResolver: letsencrypt
  #       domains:
  #         - main: "tripsit.io"
  #           sans: "*.tripsit.io"
  #         - main: "tripbot.info"
  #           sans: "*.tripbot.info"
  #         # - main: "${LEGACY_DOMAIN}"
  #         #   sans: "*.${LEGACY_DOMAIN}"

providers:
  docker:
    # endpoint: "unix:///var/run/docker.sock" # Listen to the UNIX Docker socket
    endpoint: "tcp://socket-proxy:2375"       # Listen to the UNIX Docker socket
    exposedByDefault: false                   # Only expose container that are explicitly enabled (using label traefik.enabled)
    network: "traefik-net"                    # Default network to use for connections to all containers.
    swarmmode: false                          # Activates the Swarm Mode (instead of standalone Docker).
    # swarmModeRefreshSeconds: 15             # Defines the polling interval (in seconds) in Swarm Mode.
    watch: true                               # Watch Docker Swarm events
  file:
    # filename: "/etc/traefik/config.yml"     # Link to the dynamic configuration file
    directory: "/data/rules/"                 # Link to the dynamic configuration directory
    watch: true                               # Watch for modifications
  providersThrottleDuration: 10               # Configuration reload frequency
